export const FETCH_POKEMON_START = 'FETCH_POKEMON_START';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_FAILED = 'FETCH_POKEMON_FAILED';

export const FETCH_CURRENT_POKEMON_START = 'FETCH_CURRENT_POKEMON_START';
export const FETCH_CURRENT_POKEMON_SUCCESS = 'FETCH_CURRENT_POKEMON_SUCCESS';
export const FETCH_CURRENT_POKEMON_FAILED = 'FETCH_CURRENT_POKEMON_FAILED';

export const FETCH_MOVES_START = 'FETCH_MOVES_START';
export const FETCH_MOVES_SUCCESS = 'FETCH_MOVES_SUCCESS';
export const FETCH_MOVES_FAILED = 'FETCH_MOVES_FAILED';

export const SET_CURRENT_POKEMON = 'SET_CURRENT_POKEMON';
export const SET_CURRENT_MOVE = 'SET_CURRENT_MOVE';
